version: '3.1'
services:
  rabbitmq-event-stream:
    image: rabbitmq:3-management
    volumes:
      - /mnt/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: rmqadmin
      RABBITMQ_DEFAULT_PASS: casa1234
  zookeeper-event-stream:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-event-stream:
    image: 'bitnami/kafka:latest'
    depends_on: 
      - zookeeper-event-stream
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-event-stream:2181
      - ALLOW_PLAINTEXT_LISTENER=yes